(define (problem monkey1)
    (:domain monkey)
    (:objects l1 l2 l3 l4)
    (:init
        (location l1)
        (location l2)
        (location l3)
        (location l4)
        (at monkey l1)
        (onfloor)
        (at box l2)
        (at bananas l3)
        (at knife l4)
    )
    (:goal
        (hasbananas)
    )
)